### ISSUE TITLE
build context attribute map must be homogeneous

### ISSUE THREAD

**Issue by spilliams** [spilliams/terrascope#50]
During `Build()`, a `buildContext` tries to make a `cty.MapVal` out of its scope's `Attributes`. This errors because some attributes are `cty.String` and some are `cty.Number`. They need to be homogeneous for `cty.MapVal()` to succeed. Trace (from commit 26cad3):

```
13:14:47.6961  info [project] Root will be built for 4 scopes
panic: inconsistent map element types (cty.String then cty.Number)

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.MapVal(0x140003bb200)
        /Users/spencer/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/value_init.go:221 +0x488
github.com/spilliams/terrascope/pkg/terrascope.(*buildContext).Build(0x140003905a0)
        /Users/spencer/spilliams/terrascope/src/pkg/terrascope/buildcontext.go:67 +0x15c
github.com/spilliams/terrascope/pkg/terrascope.(*Project).BuildRoot(0x14000120120, {0x16bad73f4, 0xe}, {0x1049adf08, 0x0, 0x0})
        /Users/spencer/spilliams/terrascope/src/pkg/terrascope/project.go:142 +0x2fc
github.com/spilliams/terrascope/internal/cli.newRootBuildCommand.func1(0x140001fb500?, {0x140001d8de0, 0x1, 0x4?})
        /Users/spencer/spilliams/terrascope/src/internal/cli/root.go:40 +0xdc
github.com/spf13/cobra.(*Command).execute(0x140001fb500, {0x140001e5dc0, 0x3, 0x4})
        /Users/spencer/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000014600)
        /Users/spencer/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/spencer/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /Users/spencer/spilliams/terrascope/src/main.go:11 +0x20
```

**Comment by spilliams** [comment]
Could go from `map[name]cty.Value` to `map[name][cty.Type]cty.Value`...
or `map[name]cty.Value` to `map[name]cty.String`

**Comment by spilliams** [comment]
ok yeah, with converting all attributes to strings, the built `.terrascope.context.hcl` lists attributes as strings. duh. Not gonna fly.

**Comment by spilliams** [comment]
[This](https://pkg.go.dev/github.com/zclconf/go-cty/cty#MapVal) is the relevant documentation: 

> MapVal returns a Value of a map type whose element type is defined by the types of the given values, which must be homogenous.
> If the types are not all consistent (aside from elements that are of the dynamic pseudo-type) then this function will panic. It will panic also if the given map is empty, since then the element type cannot be inferred. (See also MapValEmpty.) 

And the way these values are processed (by sticking them in an `hcl.EvalContext`'s `Variables`), turning the values into a set is probably no good either: we lose the attribute name. Also `cty.SetVal` has the same homogeneity requirement.

So, what, I make an object then...

**Comment by spilliams** [comment]
That worked! cool, good.
